---
title: "A Peek into Python"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r include = FALSE}
knitr::opts_chunk$set(error = TRUE, echo = TRUE)
```

## Accessing and installing Python

```{r eval = FALSE}
install.packages("reticulate")
```

```{r}
library(reticulate)
```

> **Poll**: Were you able to install `reticulate` and `miniconda`?


## Python as a calculator

```{python}
1 + 3
1 - 3
2 * 3
2 / 3
2 // 3
3 // 2
3 % 2
11 % 3
2 ^ 3
2 ** 3
```


## Python basics: syntax

```{r}
a <- 1 + 3
a + 1
```

```{python}
# Does python have access to the object a?
a
```

```{python}
b <- 1 + 3
# What's going on?
```

```{python}
# Objects are assigned with `=`
b = 1 + 3
# Comments are still marked by `#`
print(b)
```

> **Poll:** Which of the following will throw an error?

```{r whitespace-poll, eval = FALSE}
# A
a = 1 + 3

# B
a         = 1 +       3

# C
if(a > 2)             {
         
      "so big!"
}

# D
if(a > 2) {
  "so big!"
}
```

```{python}
# A
b = 1 + 3

# B
b         = 1 +       3

# C
if           (   b   >   2  )  :  
  print(  "so low!")

# D
if (b > 2):
  print("so low!")
  
```



## Python basics: semantics

### Variables

```{r}
a <- 5
a2 <- a
a <- 6
a2
```

```{python}
b = 5
b2 = b
b = 6
print(b2)
```

```{r}
a <- c(1, 5, 3)
sort(a)
a
```

```{python}
b = [1, 5, 3]
b.sort()
print(b)
```

```{python}
b = [1, 5, 3]
b2 = b
b.sort()
b2
```

```{r}
a <- c(1, 5, 3)
a2 <- a
a <- sort(a)
a2
```

### Objects

```{python}
# These pointers have types
anumber = 3.4
type(anumber)
aword = "hello"
type(aword)

# They also have attributes, accessible with `.`
anumber.real
anumber.imag

# They also have associated methods
print(b)
type(b)
b.append(9)
print(b)

# everything is an object
type(b.append)
```

## A note about reticulate

```{python}
b
```

```{r}
py$b
a
```

```{python}
r.a
```


