---
title: "Week 3"
subtitle: "functions and methods"
author: "STAT 198/298 Fall 2020"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(message = FALSE, fig.align = "center")
library(tidyverse)
library(reticulate)
```


## Review

# Equal vs identical copies

```{python}
a = [1, 3, 5]
y = a

a is y

a[1] = 99
a is y

a = [1, 3, 5]
y = list(a)
a is y

a = [1, 3, 5]
y = a[:]
a is y
```


# Functions

# Documentation and arguments

```{python}
print(a)
?
print("hello", "world", sep = " whole wide ")
print(a, end = "victory!")
print(end = "victory!", value = a)
```

```{python}
round(3.141)
?round
round(3.141, ndigits = 2)
```


# Classes and Methods

## Strings

```{python}
a = "hello"
type(a)
dir(a)

# Attributes
a.__class__
a.__len__()
a.__contains__("h")

# Methods
a.upper()
?a.replace
a.replace("ll", "r")
?a.index
a.index("ll")
```

## Lists

```{python}
a = [1, 3, 5]
dir(a)

# Attributes
a.__class__
a.__len__()

# Methods
a.index(5)
a.count(3)
a.append(3)
a.count(3)
a.sort()

a.__doc__
?a.__sizeof__
```


## OOP in R

```{r}
x <- rnorm(100)
m1 <- lm(mpg ~ hp, data = mtcars)

class(x)
class(m1)

?plot
?plot.lm()

# Look up {forecast} documentation

summary(x)
s <- summary(m1)
typeof(s)
typeof(m1)
?print.summary.lm
```






